// lib/models/department.dart

class Department {
  final int? id;
  final String name;
  final String? description;

  const Department({this.id, required this.name, this.description});

  // Deserialize from API response JSON
  factory Department.fromJson(Map<String, dynamic> json) {
    return Department(
      id: json['id'] as int?,
      name: json['name'] as String,
      description: json['description'] as String?,
    );
  }

  // Serialize for API request body
  // id is excluded — auto-generated by the backend
  Map<String, dynamic> toJson() {
    return {'name': name, if (description != null) 'description': description};
  }

  // Create a modified copy of this Department
  Department copyWith({int? id, String? name, String? description}) {
    return Department(
      id: id ?? this.id,
      name: name ?? this.name,
      description: description ?? this.description,
    );
  }

  @override
  String toString() =>
      'Department(id: $id, name: $name, description: $description)';

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is Department &&
        other.id == id &&
        other.name == name &&
        other.description == description;
  }

  @override
  int get hashCode => Object.hash(id, name, description);
}
